name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: test  # Ensure tests pass before publishing
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Extract version from POM
        id: get_version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Get latest version from GitHub Packages
        id: get_latest_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_VERSION=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
          "https://api.github.com/orgs/ovansa/packages/maven/jdatamocker/versions" | \
          jq -r '.[0].name')

          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
          echo "Latest version on GitHub: $LATEST_VERSION"

      - name: Check if deployment is needed
        if: env.VERSION == env.LATEST_VERSION
        run: |
          echo "Version ${VERSION} already exists on GitHub Packages. Skipping deployment."
          exit 0

      - name: Build and Publish
        run: mvn deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
